//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenHouse.VisualStudio.Design.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokenHouse.VisualStudio.Design.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a page to the wizard..
        /// </summary>
        public static string Options_AddAeroPageTooltip {
            get {
                return ResourceManager.GetString("Options_AddAeroPageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a content page to the wizard..
        /// </summary>
        public static string Options_AddContentPageTooltip {
            get {
                return ResourceManager.GetString("Options_AddContentPageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a page to the wizard..
        /// </summary>
        public static string Options_AddPageTooltip {
            get {
                return ResourceManager.GetString("Options_AddPageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a title page to the wizard..
        /// </summary>
        public static string Options_AddTitlePageTooltip {
            get {
                return ResourceManager.GetString("Options_AddTitlePageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the current page from the wizard..
        /// </summary>
        public static string Options_DeletePage {
            get {
                return ResourceManager.GetString("Options_DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the current page one page towards the beginning of the wizard..
        /// </summary>
        public static string Options_MoveTowardsBegining {
            get {
                return ResourceManager.GetString("Options_MoveTowardsBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the current page one page towards the end of the wizard..
        /// </summary>
        public static string Options_MoveTowardsEnd {
            get {
                return ResourceManager.GetString("Options_MoveTowardsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Options_RemoveCancelInstruction {
            get {
                return ResourceManager.GetString("Options_RemoveCancelInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the operation.
        /// </summary>
        public static string Options_RemoveCancelMessage {
            get {
                return ResourceManager.GetString("Options_RemoveCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the current page?.
        /// </summary>
        public static string Options_RemoveInstruction {
            get {
                return ResourceManager.GetString("Options_RemoveInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be undone using Undo in Visual Studio&apos;s..
        /// </summary>
        public static string Options_RemoveMessage {
            get {
                return ResourceManager.GetString("Options_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Page.
        /// </summary>
        public static string Options_RemoveRemoveInstruction {
            get {
                return ResourceManager.GetString("Options_RemoveRemoveInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove page from the wizard.
        /// </summary>
        public static string Options_RemoveRemoveMessage {
            get {
                return ResourceManager.GetString("Options_RemoveRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Page.
        /// </summary>
        public static string Options_RemoveTitle {
            get {
                return ResourceManager.GetString("Options_RemoveTitle", resourceCulture);
            }
        }
    }
}
